[window]
decorations = "None"

[scrolling]
history = 15000

[font]
size = 12
normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold = { family = "GeistMono Nerd Font", style = "Bold" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font", style = "Bold Italic" }
